# Generated by Django 6.0.6 on 2026-06-07 00:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('anestesico', 'Anestésico'), ('instrumental', 'Instrumental'), ('resina', 'Resina'), ('cimento', 'Cimento'), ('descartavel', 'Descartável'), ('radiografia', 'Radiografia'), ('higiene', 'Higiene'), ('medicamento', 'Medicamento'), ('outro', 'Outro')], max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('quantidade_minima', models.IntegerField(default=5, verbose_name='Qtd. Mínima (alerta)')),
                ('unidade', models.CharField(help_text='Ex: unidade, caixa, frasco, ml', max_length=20)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Gaveta 3, Armário A', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Estoque',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido.')])),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('plano_odonto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano Odontológico')),
                ('convenio_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do Convênio')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('preventivo', 'Preventivo'), ('restaurador', 'Restaurador'), ('endodontia', 'Endodontia'), ('periodontia', 'Periodontia'), ('ortodontia', 'Ortodontia'), ('implante', 'Implante'), ('cirurgia', 'Cirurgia'), ('estetico', 'Estético'), ('pediatrico', 'Pediátrico'), ('outro', 'Outro')], max_length=20)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao_media', models.IntegerField(default=60, help_text='Duração em minutos')),
                ('codigo_tuss', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código TUSS')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('dentista', 'Dentista'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cro', models.CharField(max_length=20, unique=True, verbose_name='CRO')),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('dias_trabalho', models.CharField(blank=True, help_text='Ex: SEG,TER,QUA,QUI,SEX', max_length=30, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('duracao_min', models.IntegerField(default=60, verbose_name='Duração (min)')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('falta', 'Falta (não compareceu)')], default='agendada', max_length=15)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('emergencia', 'Emergência'), ('avaliacao', 'Avaliação')], default='consulta', max_length=15)),
                ('confirmada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='principal.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='principal.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=15)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('convenio', 'Convênio'), ('outro', 'Outro')], default='dinheiro', max_length=15)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('parcelas', models.IntegerField(default=1)),
                ('parcela_atual', models.IntegerField(default=1)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='principal.consulta')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='principal.paciente')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('anamnese', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamento_plano', models.TextField(blank=True, null=True, verbose_name='Plano de Tratamento')),
                ('prescricao', models.TextField(blank=True, null=True, verbose_name='Prescrição')),
                ('radiografia', models.FileField(blank=True, null=True, upload_to='prontuarios/radiografias/')),
                ('odontograma', models.JSONField(blank=True, default=dict)),
                ('proxima_consulta', models.DateField(blank=True, null=True, verbose_name='Próxima Consulta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.consulta')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='principal.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='principal.paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-data_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='ProntuarioProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, help_text='Pode diferir do valor padrão', max_digits=10)),
                ('dente', models.CharField(blank=True, help_text='Número do dente (ex: 11, 36)', max_length=10, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.procedimento')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.prontuario')),
            ],
            options={
                'verbose_name': 'Procedimento do Prontuário',
                'unique_together': {('prontuario', 'procedimento', 'dente')},
            },
        ),
        migrations.AddField(
            model_name='prontuario',
            name='procedimentos',
            field=models.ManyToManyField(related_name='prontuarios', through='principal.ProntuarioProcedimento', to='principal.procedimento'),
        ),
    ]
